version: '3.8'

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    command: python manage.py runserver 0.0.0.0:8000

  prometheus:
    image: prom/prometheus
    restart: 'no'
    volumes:
      - prometheus_data:/prometheus
    ports:
      - 9090:9090
  
  grafana:
    image: grafana/grafana
    environment:
      GF_INSTALL_PLUGINS: "grafana-clock-panel,grafana-simple-json-datasource"
    restart: 'no'
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus

volumes:
    prometheus_data: {}
    grafana_data: {}